# Generated by Django 2.1.4 on 2019-01-02 00:52

from django.db import migrations

def seed_category(apps, schema_editor):
    categories = ['INSTITUTIONAL', 'FICTION / NON-FICTION', 'MUSIC', 'POLITICS', 'ADVERTISING']
    Category = apps.get_model('projects', 'Category')
    for item in categories:
        category = Category(name=item)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_category),
    ]
