# Generated by Django 2.1.4 on 2019-01-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190102_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('english_bio', models.TextField()),
                ('spanish_bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', help_text='Select language', max_length=2),
        ),
    ]
